import { gql, useQuery } from "@apollo/client";
import type { NextPage } from "next";
import Head from "next/head";
import AnimalCard from "../components/AnimalCard";
import TestLayout from "../components/Layout";

const FETCH_ALL_ANIMALS = gql`
  query {
    fetchAllAnimals {
      id
      name
      weight
      species
      color
      gender
      dob
      imageUrl
      breed
      description
    }
  }
`;

const Home: NextPage = () => {
  const { data, loading, error } = useQuery(FETCH_ALL_ANIMALS);
  if (loading) return <p>loading</p>;
  if (error)
    return (
      <div>
        <p>ooops there is a problem</p> <p>{error.message}</p>
      </div>
    );
  const animals = data?.fetchAllAnimals;
  return (
    <div className="flex flex-col min-h-screen bg-gray-50">
      <Head>
        <title>Animal Shelter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <TestLayout>
        <div className="container flex flex-col mx-auto my-10">
          <ul className="flex flex-wrap justify-center grid-cols-1 md:grid md:grid-cols-2 lg:grid-cols-3 gap-5">
            {animals &&
              animals.map((animal: any, key: any) => (
                <li
                  key={key}
                  className="flex flex-col max-w-md my-2 shadow bg-white rounded h-auto"
                >
                  <AnimalCard
                    image={animal.imageUrl}
                    species={animal.species}
                    name={animal.name}
                    dob={animal.dob}
                    weight={animal.weight}
                    breed={animal.breed}
                    color={animal.color}
                    id={animal.id}
                    description={animal.description}
                  />
                </li>
              ))}
          </ul>
        </div>
      </TestLayout>
    </div>
  );
};

export default Home;
