import { gql, useQuery } from "@apollo/client";
import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import AnimalCard from "../components/AnimalCard";
import Layout from "../components/Layout";
import { SearchAlt } from "@styled-icons/boxicons-regular/SearchAlt";
import { TextBulletListAdd } from "@styled-icons/fluentui-system-regular/TextBulletListAdd";
import { useRouter } from "next/router";
import { heros } from "../data/imageHeros";
import ImageSlider from "../components/ImageSlider";
export const FETCH_ALL_ANIMALS = gql`
  query {
    fetchAllAnimals {
      id
      name
      weight
      species
      color
      gender
      dob
      imageUrl
      breed
      description
    }
  }
`;

const Home: NextPage = () => {
  const router = useRouter();
  const { data, loading, error } = useQuery(FETCH_ALL_ANIMALS);

  if (loading)
    return (
      <div className="flex flex-col min-h-screen bg-zinc-50">
        <Head>
          <title>PetConnect</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <style>
            @import
            url('https://fonts.googleapis.com/css2?family=Hubballi&family=Titillium+Web:ital,wght@0,200;0,300;0,400;0,600;0,700;0,900;1,200;1,300;1,400;1,600;1,700&family=Work+Sans:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap');
          </style>
        </Head>
        <Layout>
          <ImageSlider />

          <div className="bg-purple-600 w-full md:max-w-2xl md:self-center md:rounded-full md:h-14 md:mt-10 mb-5 h-20 grid grid-cols-2 divide-x-2 divide-purple-800">
            <button
              aria-label="Find a pet"
              onClick={() => router.push("/animals/findpet")}
              className="flex items-center justify-center w-full text-white text-3xl font-extrabold font-Hubballi"
            >
              <div className="w-10">
                <SearchAlt />
              </div>
              Find a pet
            </button>

            <button
              aria-label="Create new pet listing"
              onClick={() => router.push("/animals/createnewlisting")}
              className="flex items-center justify-center w-full text-white text-3xl font-extrabold font-Hubballi"
            >
              <div className="w-10 mr-1">
                <TextBulletListAdd />
              </div>
              List a pet
            </button>
          </div>

          <div className="container flex flex-col mx-auto">
            <h2 className="text-4xl font-Titillium-Web text-center text-purple-800">
              Featured Pets
            </h2>
            <ul className="flex flex-wrap justify-center grid-cols-1 md:grid md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-5 my-3">
              <li className="flex flex-col animate-pulse max-w-md my-2 shadow bg-gray-200 h-44 rounded"></li>
              <li className="flex flex-col animate-pulse max-w-md my-2 shadow bg-gray-200 h-44 rounded"></li>
              <li className="flex flex-col animate-pulse max-w-md my-2 shadow bg-gray-200 h-44 rounded"></li>
              <li className="flex flex-col animate-pulse max-w-md my-2 shadow bg-gray-200 h-44 rounded"></li>
              <li className="flex flex-col animate-pulse max-w-md my-2 shadow bg-gray-200 h-44 rounded"></li>
              <li className="flex flex-col animate-pulse max-w-md my-2 shadow bg-gray-200 h-44 rounded"></li>
              <li className="flex flex-col animate-pulse max-w-md my-2 shadow bg-gray-200 h-44 rounded"></li>
            </ul>
          </div>
        </Layout>
      </div>
    );
  if (error)
    return (
      <div>
        <p>ooops there is a problem</p> <p>{error.message}</p>
      </div>
    );

  const animals = data?.fetchAllAnimals;
  let randomizedAnimals = [...animals];
  randomizedAnimals.sort(() => Math.random() - 0.5);
  console.log(randomizedAnimals);
  return (
    <div className="flex flex-col min-h-screen bg-zinc-50">
      <Head>
        <title>PetConnect</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <style>
          @import
          url('https://fonts.googleapis.com/css2?family=Hubballi&family=Titillium+Web:ital,wght@0,200;0,300;0,400;0,600;0,700;0,900;1,200;1,300;1,400;1,600;1,700&family=Work+Sans:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap');
        </style>
      </Head>
      <Layout>
        <ImageSlider />
        <div className="bg-purple-600 w-full md:max-w-2xl md:self-center md:rounded-full md:h-14 md:mt-10 mb-5 h-20 grid grid-cols-2 divide-x-2 divide-purple-800">
          <button
            aria-label="Find a pet"
            onClick={() => router.push("/animals/findpet")}
            className="flex items-center justify-center w-full text-white text-3xl font-extrabold font-Hubballi"
          >
            <div className="w-10">
              <SearchAlt />
            </div>
            Find a pet
          </button>

          <button
            aria-label="Create new pet listing"
            onClick={() => router.push("/animals/createnewlisting")}
            className="flex items-center justify-center w-full text-white text-3xl font-extrabold font-Hubballi"
          >
            <div className="w-10 mr-1">
              <TextBulletListAdd />
            </div>
            List a pet
          </button>
        </div>

        <div className="container flex flex-col mx-auto">
          <h2 className="text-4xl font-Titillium-Web text-center text-purple-800">
            Featured Pets
          </h2>
          <ul className="flex flex-wrap justify-center grid-cols-1 md:grid md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-5 my-3">
            {randomizedAnimals &&
              randomizedAnimals.map((animal: any, key: any) => (
                <li
                  key={key}
                  className="flex flex-col max-w-md my-2 shadow bg-white rounded h-auto"
                >
                  <AnimalCard
                    image={animal.imageUrl}
                    species={animal.species}
                    name={animal.name}
                    dob={animal.dob}
                    weight={animal.weight}
                    breed={animal.breed}
                    color={animal.color}
                    id={animal.id}
                    description={animal.description}
                  />
                </li>
              ))}
          </ul>
        </div>
      </Layout>
    </div>
  );
};

export default Home;
