import { gql, useQuery } from "@apollo/client";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import AnimalCard from "../components/AnimalCard";
import Layout from "../components/Layout";
import { SearchAlt } from "@styled-icons/boxicons-regular/SearchAlt";
import { TextBulletListAdd } from "@styled-icons/fluentui-system-regular/TextBulletListAdd";
import { useRouter } from "next/router";
import { heros } from "../data/imageHeros";
const FETCH_ALL_ANIMALS = gql`
  query {
    fetchAllAnimals {
      id
      name
      weight
      species
      color
      gender
      dob
      imageUrl
      breed
      description
    }
  }
`;

const Home: NextPage = () => {
  const router = useRouter();
  const { data, loading, error } = useQuery(FETCH_ALL_ANIMALS);
  const [sliderIndex, setSliderIndex] = useState(0);
  const [sliderImage, setSliderImage] = useState("");
  useEffect(() => {
    setSliderImage(heros[sliderIndex]);
  });

  if (loading) return <p>loading</p>;
  if (error)
    return (
      <div>
        <p>ooops there is a problem</p> <p>{error.message}</p>
      </div>
    );
  const animals = data?.fetchAllAnimals;
  return (
    <div className="flex flex-col min-h-screen bg-gray-50">
      <Head>
        <title>PetConnect</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className="flex relative justify-center items-center flex-col w-full bg-purple-700 h-96 sm:h-102  shadow">
          <img
            src={sliderImage}
            alt="Hero"
            className="w-full object-cover h-full"
          />
          <div className="flex sm:relative w-full max-w-6xl h-auto justify-center items-center">
            <div className="flex absolute bg-purple-500 px-3 py-2 rounded-full text-lg text-white bottom-10 sm:bottom-10 sm:left-20 shadow-lg duration-150 border-2 border-purple-700 hover:bg-purple-600 hover:cursor-pointer">
              <button>Get Started</button>
            </div>
          </div>
          <div className="flex group p-4  w-min absolute justify-center items-center top-0 mx-auto ">
            <button
              onClick={() => {
                setSliderIndex(0);
              }}
              className="bg-purple-300 opacity-60 hover:bg-purple-500 duration-150 group-hover:opacity-100 w-8 h-2 mx-2 shadow rounded-full"
            ></button>
            <button
              onClick={() => {
                setSliderIndex(1);
              }}
              className="bg-purple-300 opacity-60 hover:bg-purple-500 duration-150 group-hover:opacity-100 w-8 h-2 mx-2 shadow rounded-full"
            ></button>
            <button
              onClick={() => {
                setSliderIndex(2);
              }}
              className="bg-purple-300 opacity-60 hover:bg-purple-500 duration-150 group-hover:opacity-100 w-8 h-2 mx-2 shadow rounded-full"
            ></button>
            <button
              onClick={() => {
                setSliderIndex(3);
              }}
              className="bg-purple-300 opacity-60 hover:bg-purple-500 duration-150 group-hover:opacity-100 w-8 h-2 mx-2 shadow rounded-full"
            ></button>
          </div>
        </div>
        <div className="bg-purple-600 w-full md:max-w-2xl md:self-center md:rounded-full md:h-14 md:mt-10 mb-5 h-20 grid grid-cols-2 divide-x-2 divide-purple-800">
          <button
            onClick={() => router.push("/animals/findpet")}
            className="flex items-center justify-center w-full text-white text-2xl"
          >
            <div className="w-10">
              <SearchAlt />
            </div>
            Find a pet
          </button>

          <button
            onClick={() => router.push("/animals/addpet")}
            className="flex items-center justify-center w-full text-white text-2xl"
          >
            <div className="w-10 mr-1">
              <TextBulletListAdd />
            </div>
            List a pet
          </button>
        </div>

        <div className="container flex flex-col mx-auto">
          <h2 className="text-4xl font-light text-center text-purple-800 mb-2">
            Featured Pets
          </h2>
          <ul className="flex flex-wrap justify-center grid-cols-1 md:grid md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-5 my-5">
            {animals &&
              animals.map((animal: any, key: any) => (
                <li
                  key={key}
                  className="flex flex-col max-w-md my-2 shadow bg-white rounded h-auto"
                >
                  <AnimalCard
                    image={animal.imageUrl}
                    species={animal.species}
                    name={animal.name}
                    dob={animal.dob}
                    weight={animal.weight}
                    breed={animal.breed}
                    color={animal.color}
                    id={animal.id}
                    description={animal.description}
                  />
                </li>
              ))}
          </ul>
        </div>
      </Layout>
    </div>
  );
};

export default Home;
